version: "3"

services:

  jenkins-project:
    build: .
    ports:
      - 5005:5005
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
      - ".:/opt/jenkins-project"
      - "/opt/jenkins-project/target"
      - "/opt/jenkins-project/project/target"
      - "/root/.sbt/1.0/plugins"